import Sidebar from "@/modules/pages/dashboard/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Dashboard | CMS portfolio",
    description: "Hey this is me Muhammad Ashraful Alam; Generated by github.com/muhamash",
    keywords: 'Muhamash, Md Ashraful Alam, Full Stack Developer, React, Node.js, Web Development, Portfolio, Muhammad Ashraful Alam, Dashboard',
    authors: [ { name: 'Ashraful', url: 'https://muhamash-studio.vercel.app/' } ],
    creator: 'Ashraful',
};

export default async function DashBoardLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}> )
{

  return (
    <Sidebar>
      {children}
    </Sidebar>
  );
}