import PageTransition from "@/modules/layouts/PageTransition";
import AuthProvider from "@/providers/authProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Md Ashraful Alam | CMS portfolio",
  description: "Hey this is me Muhammad Ashraful Alam; Generated by github.com/muhamash",
  keywords: 'Muhamash, Md Ashraful Alam, Full Stack Developer, React, Node.js, Web Development, Portfolio, Muhammad Ashraful Alam',
  authors: [ { name: 'Ashraful', url: 'https://muhamash-studio.vercel.app/' } ],
  creator: 'Ashraful',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://muhamash-studio.vercel.app/',
    title: 'Md Ashraful Alam - Full Stack Developer',
    description: 'Portfolio website showcasing my work in web development and design',
    siteName: 'Ashraful CMS Portfolio',
    images: [
      {
        url: '/me.jpeg',
        width: 1200,
        height: 630,
        alt: 'Ashraful Portfolio',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Ashraful - Full Stack Developer',
    description: 'Portfolio website showcasing my work in web development and design',
    creator: 'github.com/muhamash',
    images: [ '/me.jpeg' ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ geistSans.variable } ${ geistMono.variable } antialiased`}
      >
        <PageTransition>
          <AuthProvider>
            {children}
            <Toaster position="top-center"/>
          </AuthProvider>
        </PageTransition>
      </body>
    </html>
  );
}
