import { getAllBlogs } from "@/lib/utils/blogs.util";
import { getHomePageData } from "@/lib/utils/page.utils";
import { getAllProjects } from "@/lib/utils/projects.utils";
import BlogSection from "@/modules/pages/home/BlogSection";
import ContactSection from "@/modules/pages/home/ContactSection";
import { HeroSection } from "@/modules/pages/home/Hero";
import ProjectSection from "@/modules/pages/home/ProjectSection";
import { Calendar1Icon, MapPinCheck } from "lucide-react";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Md Ashraful Alam | CMS portfolio",
  description: "Hey this is me Muhammad Ashraful Alam; Generated by github.com/muhamash",
  keywords: 'Muhamash, Md Ashraful Alam, Full Stack Developer, React, Node.js, Web Development, Portfolio, Muhammad Ashraful Alam',
  authors: [ { name: 'Ashraful', url: 'https://muhamash-studio.vercel.app/' } ],
  creator: 'Ashraful',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://cms-portfolio-livid.vercel.app/',
    title: 'Md Ashraful Alam - Full Stack Developer',
    description: 'Portfolio website showcasing my work in web development and design',
    siteName: 'Ashraful CMS Portfolio',
    images: [
      {
        url: '/me.jpeg',
        width: 1200,
        height: 630,
        alt: 'Ashraful Portfolio',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Ashraful - Full Stack Developer',
    description: 'Portfolio website showcasing my work in web development and design',
    creator: 'github.com/muhamash',
    images: [ '/me.jpeg' ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default async function Home ()
{

  const allProjects = await getAllProjects();
  const allBlogs = await getAllBlogs();
  const homePage = await getHomePageData()
  // console.log(homePage)

  return (
    <div className="py-30 grow-1 px-6 md:px-12 container mx-auto overflow-x-hidden">
      <HeroSection homepageData={homePage} />
      
      {/* insight about me */}
      <div className="flex flex-col items-center justify-center">
        <div className="flex flex-col items-center gap-4 mb-6">
          <h3 className="text-2xl md:text-4xl font-bold text-pink-800 font-mono">{homePage?.personalInfo?.name}</h3>
            <p className="text-orange-800 text-lg md:text-xl">{homePage?.personalInfo?.title}</p>
        </div>

        <div className="space-y-4 mb-6 flex flex-col items-center justify-around">
          <div className="flex items-center gap-3 text-sm">
            <MapPinCheck size={16} className="text-primary" />
            <span>{homePage?.personalInfo.address}</span>
          </div>
          <div className="flex items-center gap-3 text-sm">
            <Calendar1Icon size={16} className="text-primary" />
            <span>Available for freelance</span>
          </div>
        </div>

        <p className="text-muted-foreground leading-relaxed text-center">
          {homePage?.headerAboutAddress}
        </p>
      </div>

      {/* project section */}
      <Suspense fallback={
        <p>Loading..</p>
      }>
        <ProjectSection projects={allProjects?.data} />
      </Suspense>
      
      {/* blog section */}
      <Suspense fallback={
        <p>Loading..</p>
      }>
        <BlogSection blogs={allBlogs?.data} />
      </Suspense>
      
      {/* contact section */}
      <ContactSection data={ homePage?.personalInfo } />
    </div>
  );
}
